server:
  port : 8082
grpc:
  server:
    port: 8182
---
spring.application.name: "service-B"
spring.profiles.active: local
spring.profiles.include: "rabbitmq,sleuth"
---
spring:
  profiles: "rabbitmq"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
---
spring:
  profiles: "sleuth"
  sleuth:
    propagation:
      type: B3 #,W3C
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
---
management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http: false
      sla:
        http:
          server:
            requests: 1ms,20ms,50ms,100ms,200ms,500ms,1s,2s,5s,10s,10s,50s