server:
  port : 8082
grpc:
  server:
    port: 8182

spring:
  application:
    name: service-B
  profiles:
    active: local
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  sleuth:
    propagation:
      type: B3 #,W3C
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411