version: "3.4"
services:
  service-a:
    build: ./service-A
    container_name: 'service-A'
    environment:
      - spring_profiles_active=docker
    ports:
      - 8081:8081
  service-b:
    build: ./service-B
    container_name: 'service-B'
    environment:
      - spring_profiles_active=docker
    ports:
      - 8082:8082
      - 8182:8182
  service-c:
    build: ./service-C
    container_name: 'service-C'
    environment:
      - spring_profiles_active=docker
    ports:
      - 8083:8083
      - 8183:8183
  service-d:
    build: ./service-D
    container_name: 'service-D'
    environment:
      - spring_profiles_active=docker
    ports:
      - 8084:8084
      - 8184:8184