server:
  port : 8083
grpc:
  server:
    port: 8183
---
spring.application.name: "service-C"
spring.profiles.active: local
spring.profiles.include: "mysql,redis"
---
spring:
  profiles: "mysql"
  datasource:
    url: "jdbc:mysql://localhost:3306/service_c"
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
---
spring:
  profiles: "redis"
  redis:
    redisson:
      file: classpath:redisson.yml