server:
  port : 8083
grpc:
  server:
    port: 8183
---
spring.application.name: "service-C"
spring.profiles.active: local
spring.profiles.include: "mysql,redis"
---
spring:
  profiles: "mysql"
  datasource:
    url: "jdbc:mysql://localhost:3306/service_c"
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
---
spring:
  profiles: "redis"
  redis:
    redisson:
      file: classpath:redisson.yml
---
spring:
  profiles: "sleuth"
  sleuth:
    propagation:
      type: B3 #,W3C
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
---
management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http: false
      sla:
        http:
          server:
            requests: 1ms,20ms,50ms,100ms,200ms,500ms,1s,2s,5s,10s,10s,50s