server:
  port : 8081
grpc:
  port: 8181
---
spring.application.name: "service-A"
spring.profiles.active: local
spring.profiles.include: "sleuth,kafka"
---
grpc:
  client:
    serviceb:
      address: static://localhost:8182
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    servicec:
      address: static://localhost:8183
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
---
spring:
  profiles: "sleuth"
  sleuth:
    propagation:
      type: B3 #,W3C
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
---
spring:
  profiles: "kafka"
  kafka:
    bootstrap-servers: "localhost:9093"
---
management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http: false
      sla:
        http:
          server:
            requests: 1ms,20ms,50ms,100ms,200ms,500ms,1s,2s,5s,10s,10s,50s
