grpc.client.serviceb.address: static://${SERVICE_A_HOST}:8182
grpc.client.servicec.address: static://${SERVICE_A_HOST}:8182
spring.zipkin.base-url: http://${ZIPKIN_HOST}:9411
spring.kafka.bootstrap-servers: ${KAFKA_HOST}:9093