server:
  port : 8081
grpc:
  port: 8181
  client:
    serviceb:
      address: static://localhost:8182
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    servicec:
      address: static://localhost:8183
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    serviced:
      address: static://localhost:8184
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
spring:
  profiles:
    active: local
  application:
    name: "service-A"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    redisson:
      file: classpath:/redisson.yaml
  kafka:
    bootstrap-servers: "localhost:9093"
    listener:
      missing-topics-fatal: false