server:
  port : 8084
grpc:
  server:
    port: 8184
---
spring.application.name: "service-D"
spring.profiles.active: local
spring.profiles.include: "kafka,sleuth"
---
spring:
  profiles: "kafka"
  kafka:
    bootstrap-servers: "localhost:9093"
    listener:
      missing-topics-fatal: false
---
spring:
  profiles: "sleuth"
  sleuth:
    propagation:
      type: B3 #,W3C
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
---
management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http: false
      sla:
        http:
          server:
            requests: 1ms,20ms,50ms,100ms,200ms,500ms,1s,2s,5s,10s,10s,50s