server:
  port : 8084
grpc:
  server:
    port: 8184

spring:
  application:
    name: service-D
  profiles:
    active: local
  kafka:
    bootstrap-servers: "localhost:9093"
    listener:
      missing-topics-fatal: false
  sleuth:
    propagation:
      type: B3 #,W3C
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411