CREATE DATABASE IF NOT EXISTS sa-sample;

--CREATE USER 'user'@'%' IDENTIFIED BY 'password';
--GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `sa-sample`.* TO
--'user'@'%';
--FLUSH PRIVILEGES;

USE sa-sample;
CREATE TABLE Bank (
  bank_id INT(11) NOT NULL,
  create_time BIGINT(20) NOT NULL,
  PRIMARY KEY (bank_id)
);